export const GET_CARDS = "GET_CARDS"
export const SIGN_UP = "SIGN_UP"
export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const CREATE_READING = "CREATE_READING"
export const SAVE_CARDS = "SAVE_CARDS"
export const GET_READING = "GET_READING"